name = "vectorize-processor"
main = "src/workers/vectorize-processor.js"
compatibility_date = "2024-10-01"

# AI binding for embeddings
[ai]
binding = "AI"

# Vectorize binding
[[vectorize]]
binding = "VECTORS"
index_name = "knowledge_embeddings"

# Queue consumer
[[queues.consumers]]
queue = "vectorize-queue"
max_batch_size = 10
max_batch_timeout = 30
