name = "cloudcurio-blog"
compatibility_date = "2024-10-01"
pages_build_output_dir = "public"

# D1 Database for knowledge base
[[d1_databases]]
binding = "DB"
database_name = "knowledge_base"
database_id = "local-db-id"

# Vectorize for embeddings
[[vectorize]]
binding = "VECTORS"
index_name = "knowledge_embeddings"

# R2 Bucket for storage
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudcurio-storage"

# AI binding
[ai]
binding = "AI"

# KV for blog posts cache
[[kv_namespaces]]
binding = "BLOG_CACHE"
id = "local-kv-id"

# Workers AI models
[vars]
AI_GATEWAY = "cloudcurio-ai"
